apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctorya-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctorya-app
  template:
    metadata:
      labels:
        app: doctorya-app
    spec:
      containers:
        - name: app
          image: localhost/doctorya-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "250Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: HOST_DB
              value: doctorya-db
            - name: PORT_DB
              value: "5432"
            - name: POSTGRES_DB
              value: doctorya
            - name: USERNAME_DB
              value: postgres
            - name: PASSWORD_DB
              value: root
---
apiVersion: v1
kind: Service
metadata:
  name: doctorya-app
spec:
  type: NodePort
  selector:
    app: doctorya-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: doctorya-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: doctorya-app
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80