apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermanagement-app
  template:
    metadata:
      labels:
        app: usermanagement-app
    spec:
      containers:
        - name: app
          image: localhost/usermanagement-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "250Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: usermanagement-app
spec:
  type: NodePort
  selector:
    app: usermanagement-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: usermanagement-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: usermanagement-app
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80